doctrine:
    dbal:
        url: '%env(default:stocking_database_url:STOCKING_DATABASE_URL)%'
    orm:
        enable_native_lazy_objects: true
        auto_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            Stocking:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Stocking\Entity'
                alias: Stocking
